cursor            #e8b6f0
cursor_text_color #472151

foreground            #eae0e7
background            #110d11
selection_foreground  #3a2b3d
selection_background  #d6c0d6
url_color             #d6c0d6

#: black 000000 767676
color0  #161217
color8  #393338
#: red cc0403 f2201f
color1  #904084
color9  #d198c9
#: green 19cb00 23fd00
color2  #d6c0d6
color10 #f3dbf2
#: yellow cecb00 fffd00
color3  #f5b7b1
color11 #ffdad6
#: blue 0d73cc 1a8fff
color4  #5f3869
color12 #e8b6f0
#: magenta cb1ed1 fd28ff
color5  #524154
color13 #d6c0d6
#: cyan 0dcdcd 14ffff
color6  #673b37
color14 #f5b7b1
#: white dddddd ffffff
color7  #cfc3cd
color15 #eae0e7

mark1_foreground #2f0a3a
mark1_background #fcd7ff
mark2_foreground #241727
mark2_background #f3dbf2
mark3_foreground #33110e
mark3_background #ffdad6

active_tab_foreground #472151
active_tab_background #e8b6f0
inactive_tab_foreground #fcd7ff
inactive_tab_background #5f3869

active_border_color #e8b6f0
inactive_border_color #472151
# bell_border_color #ff5a00
