# ...
[templates.kitty]
input_path = '~/.config/matugen/templates/kitty-colors.conf'
output_path = '~/.config/kitty/themes/Matugen.conf'
post_hook = "kitty +kitten themes --reload-in=all Matugen"
# ...

[config]
# ...
[templates.yazi]
input_path = '~/.config/matugen/templates/yazi-theme.toml'
output_path = '~/.config/yazi/theme.toml'
# ...

# ...
[templates.btop]
input_path = '~/.config/matugen/templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'
post_hook = 'pkill -USR2 btop || true'
# ...

# ...
[templates.fuzzel]
input_path = '~/.config/matugen/templates/fuzzel.ini'
output_path = '~/.config/fuzzel/colors.ini'
# ...

# ...
[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland-colors.lua'
output_path = '~/.config/hypr/colors.lua'
# ...

[templates.cava]
input_path = '~/.config/matugen/templates/cava-colors.ini'
output_path = '~/.config/cava/themes/matugen'

# ...
[templates.dunst]
input_path = '~/.config/matugen/templates/dunstrc-colors'
output_path = '~/.config/dunst/dunstrc'
post_hook = 'dunstctl reload'
# ...

# ...
[templates.steam]
input_path = '~/.config/matugen/templates/steam.css'
output_path = '~/.config/AdwSteamGtk/custom.css'
post_hook =  'adwaita-steam-gtk -i'
# ..

# ...
[templates.obs]
input_path = '~/.config/matugen/templates/matugen.obt'
output_path = '~/.config/obs-studio/themes/matugen.obt'
# ...

# ...
[templates.obsidian]
input_path = '~/.config/matugen/templates/obsidian.css'
output_path = "/home/pirate/Obsidian-Vault/Pirates' Vault/.obsidian/snippets/matugen.css"
# ...

# ...
[templates.starship]
input_path = '~/.config/matugen/templates/starship-colors.toml'
output_path = '~/.config/starship.toml'
# ...

