const CATEGORIES = [
    { id: "smileys", icon: "😀", name: "Smileys & Emotion" },
    { id: "people", icon: "👋", name: "People & Body" },
    { id: "animals", icon: "🐶", name: "Animals & Nature" },
    { id: "food", icon: "🍕", name: "Food & Drink" },
    { id: "activities", icon: "⚽", name: "Activities" },
    { id: "travel", icon: "🚗", name: "Travel & Places" },
    { id: "objects", icon: "💡", name: "Objects" },
    { id: "symbols", icon: "❤️", name: "Symbols" }
];

const EMOJIS = [
    // Smileys & Emotion
    { emoji: "😀", category: "smileys", name: "grinning face", keywords: "smile grinning face happy joy" },
    { emoji: "😃", category: "smileys", name: "grinning face with big eyes", keywords: "happy joy smile face" },
    { emoji: "😄", category: "smileys", name: "grinning face with smiling eyes", keywords: "happy joy smile face" },
    { emoji: "😁", category: "smileys", name: "beaming face with smiling eyes", keywords: "happy joy smile face grin" },
    { emoji: "😆", category: "smileys", name: "grinning squinting face", keywords: "happy joy smile face laugh" },
    { emoji: "😅", category: "smileys", name: "grinning face with sweat", keywords: "happy hot sweat exercise laugh" },
    { emoji: "😂", category: "smileys", name: "face with tears of joy", keywords: "happy tears joy cry laugh lol" },
    { emoji: "🤣", category: "smileys", name: "rolling on the floor laughing", keywords: "happy tears joy laugh lol rofl" },
    { emoji: "😊", category: "smileys", name: "smiling face with smiling eyes", keywords: "happy joy smile face blush" },
    { emoji: "😇", category: "smileys", name: "smiling face with halo", keywords: "angel innocent heaven happy" },
    { emoji: "🙂", category: "smileys", name: "slightly smiling face", keywords: "smile face simple" },
    { emoji: "🙃", category: "smileys", name: "upside-down face", keywords: "silly crazy face smile" },
    { emoji: "😉", category: "smileys", name: "winking face", keywords: "wink smile face" },
    { emoji: "😌", category: "smileys", name: "relieved face", keywords: "relieved calm peace rest sleep" },
    { emoji: "😍", category: "smileys", name: "smiling face with heart-eyes", keywords: "love heart eyes like beautiful" },
    { emoji: "🥰", category: "smileys", name: "smiling face with hearts", keywords: "love hearts blush happy like" },
    { emoji: "😘", category: "smileys", name: "face blowing a kiss", keywords: "love kiss heart face" },
    { emoji: "😗", category: "smileys", name: "kissing face", keywords: "kiss face" },
    { emoji: "😙", category: "smileys", name: "kissing face with smiling eyes", keywords: "kiss face happy" },
    { emoji: "😚", category: "smileys", name: "kissing face with closed eyes", keywords: "kiss face blush" },
    { emoji: "😋", category: "smileys", name: "face savoring food", keywords: "tongue delicious food yummy eat" },
    { emoji: "😛", category: "smileys", name: "face with tongue", keywords: "tongue silly face" },
    { emoji: "😝", category: "smileys", name: "squinting face with tongue", keywords: "tongue silly face squint" },
    { emoji: "😜", category: "smileys", name: "winking face with tongue", keywords: "tongue silly face wink" },
    { emoji: "🤪", category: "smileys", name: "zany face", keywords: "crazy silly zany face eye" },
    { emoji: "🤨", category: "smileys", name: "face with raised eyebrow", keywords: "suspicious eyebrow face doubt question" },
    { emoji: "🧐", category: "smileys", name: "face with monocle", keywords: "monocle classy smart face find search" },
    { emoji: "🤓", category: "smileys", name: "nerd face", keywords: "nerd smart geek glasses face" },
    { emoji: "😎", category: "smileys", name: "smiling face with sunglasses", keywords: "cool sunglasses sun style face" },
    { emoji: "🥸", category: "smileys", name: "disguised face", keywords: "disguise mask mustache glasses face" },
    { emoji: "🤩", category: "smileys", name: "star-struck", keywords: "star eyes happy amazed face" },
    { emoji: "🥳", category: "smileys", name: "partying face", keywords: "party celebrate hat horn happy face" },
    { emoji: "😏", category: "smileys", name: "smirking face", keywords: "smirk silly face tease" },
    { emoji: "😒", category: "smileys", name: "unamused face", keywords: "unamused face boring sad sigh" },
    { emoji: "😞", category: "smileys", name: "disappointed face", keywords: "disappointed sad face cry" },
    { emoji: "😔", category: "smileys", name: "pensive face", keywords: "pensive sad face worry" },
    { emoji: "😟", category: "smileys", name: "worried face", keywords: "worried sad face fear" },
    { emoji: "😕", category: "smileys", name: "confused face", keywords: "confused face question puzzle" },
    { emoji: "🙁", category: "smileys", name: "slightly frowning face", keywords: "frown sad face" },
    { emoji: "☹️", category: "smileys", name: "frowning face", keywords: "frown sad face" },
    { emoji: "😣", category: "smileys", name: "persevering face", keywords: "struggle pain face" },
    { emoji: "😖", category: "smileys", name: "confounded face", keywords: "struggle pain face confounded" },
    { emoji: "😫", category: "smileys", name: "tired face", keywords: "tired sleep yawn face" },
    { emoji: "😩", category: "smileys", name: "weary face", keywords: "tired sleep weary face" },
    { emoji: "🥺", category: "smileys", name: "pleading face", keywords: "please beg puppy eyes face" },
    { emoji: "😢", category: "smileys", name: "crying face", keywords: "cry tears sad face" },
    { emoji: "😭", category: "smileys", name: "loudly crying face", keywords: "cry tears sad face sob stream" },
    { emoji: "😤", category: "smileys", name: "face with steam from nose", keywords: "angry steam nose win face" },
    { emoji: "😠", category: "smileys", name: "angry face", keywords: "angry mad face" },
    { emoji: "😡", category: "smileys", name: "enraged face", keywords: "angry mad face red enraged" },
    { emoji: "🤬", category: "smileys", name: "face with symbols on mouth", keywords: "angry swear curse face mad" },
    { emoji: "🤯", category: "smileys", name: "exploding head", keywords: "explode mind head blow face" },
    { emoji: "😳", category: "smileys", name: "flushed face", keywords: "flushed blush face surprise embarrassed" },
    { emoji: "🥵", category: "smileys", name: "hot face", keywords: "hot red sweat fever face" },
    { emoji: "🥶", category: "smileys", name: "cold face", keywords: "cold blue freeze ice face" },
    { emoji: "😱", category: "smileys", name: "face screaming in fear", keywords: "fear scream scary face home alone" },
    { emoji: "😨", category: "smileys", name: "fearful face", keywords: "fear scary face" },
    { emoji: "😰", category: "smileys", name: "anxious face with sweat", keywords: "fear sweat worry face anxious" },
    { emoji: "😥", category: "smileys", name: "sad but relieved face", keywords: "relieved sad sweat face" },
    { emoji: "😓", category: "smileys", name: "downcast face with sweat", keywords: "sad sweat face worry" },
    { emoji: "🤔", category: "smileys", name: "thinking face", keywords: "think query question face" },
    { emoji: "🫣", category: "smileys", name: "face with peeking eye", keywords: "peek scare hide look eye face" },
    { emoji: "🤭", category: "smileys", name: "face with hand over mouth", keywords: "gasp oops laugh hand mouth face" },
    { emoji: "🫢", category: "smileys", name: "face with open eyes and hand over mouth", keywords: "gasp surprise shock hand mouth face" },
    { emoji: "🫡", category: "smileys", name: "saluting face", keywords: "salute respect army military face" },
    { emoji: "🤫", category: "smileys", name: "shushing face", keywords: "shush quiet silent whisper face" },
    { emoji: "🫠", category: "smileys", name: "melting face", keywords: "melt hot disappear face" },
    { emoji: "🤥", category: "smileys", name: "lying face", keywords: "lie nose long pinocchio face" },
    { emoji: "😐", category: "smileys", name: "neutral face", keywords: "neutral okay normal face" },
    { emoji: "😑", category: "smileys", name: "expressionless face", keywords: "expressionless deadpan face ok" },
    { emoji: "😬", category: "smileys", name: "grimacing face", keywords: "grimace teeth awkward face" },
    { emoji: "🙄", category: "smileys", name: "face with rolling eyes", keywords: "roll eyes bore meh face" },
    { emoji: "😯", category: "smileys", name: "hushed face", keywords: "hushed gasp surprise face" },
    { emoji: "😦", category: "smileys", name: "frowning face with open mouth", keywords: "frown open mouth gasp face" },
    { emoji: "😧", category: "smileys", name: "anguished face", keywords: "anguish sad surprise face" },
    { emoji: "😮", category: "smileys", name: "face with open mouth", keywords: "open mouth gasp surprise face" },
    { emoji: "😲", category: "smileys", name: "astonished face", keywords: "astonished surprise shock face" },
    { emoji: "🥱", category: "smileys", name: "yawning face", keywords: "yawn sleep tired face" },
    { emoji: "😴", category: "smileys", name: "sleeping face", keywords: "sleep tired zzz face" },
    { emoji: "🤤", category: "smileys", name: "drooling face", keywords: "drool sleep tasty face" },
    { emoji: "😪", category: "smileys", name: "sleepy face", keywords: "sleep tired tear snot face" },
    { emoji: "😵", category: "smileys", name: "face with crossed-out eyes", keywords: "dizzy dead cross eyes face" },
    { emoji: "😵‍💫", category: "smileys", name: "face with spiral eyes", keywords: "dizzy spiral eyes loop face" },
    { emoji: "🤐", category: "smileys", name: "zipper-mouth face", keywords: "zipper mouth silent secret face" },
    { emoji: "🥴", category: "smileys", name: "woozy face", keywords: "dizzy woozy drunk face" },
    { emoji: "🤢", category: "smileys", name: "nauseated face", keywords: "nausea green sick vomit face" },
    { emoji: "🤮", category: "smileys", name: "face vomiting", keywords: "vomit barf sick face" },
    { emoji: "🤧", category: "smileys", name: "sneezing face", keywords: "sneeze sick cold nose tissue face" },
    { emoji: "😷", category: "smileys", name: "face with medical mask", keywords: "mask sick doctor covid face" },
    { emoji: "🤒", category: "smileys", name: "face with thermometer", keywords: "thermometer sick fever face" },
    { emoji: "🤕", category: "smileys", name: "face with head-bandage", keywords: "bandage hurt injury head face" },
    { emoji: "🤑", category: "smileys", name: "money-mouth face", keywords: "money dollar rich face cash" },
    { emoji: "🤠", category: "smileys", name: "cowboy hat face", keywords: "cowboy hat west face sheriff" },
    { emoji: "😈", category: "smileys", name: "smiling face with horns", keywords: "devil horns purple evil smile face" },
    { emoji: "👿", category: "smileys", name: "angry face with horns", keywords: "devil horns purple evil angry face" },
    { emoji: "💀", category: "smileys", name: "skull", keywords: "skull dead bone death skeleton" },
    { emoji: "☠️", category: "smileys", name: "skull and crossbones", keywords: "skull crossbones dead danger poison pirate" },
    { emoji: "👽", category: "smileys", name: "alien", keywords: "alien space ufo martian" },
    { emoji: "👾", category: "smileys", name: "alien monster", keywords: "monster game space alien retro" },
    { emoji: "🤖", category: "smileys", name: "robot", keywords: "robot machine sci-fi computer" },
    { emoji: "🎃", category: "smileys", name: "jack-o-lantern", keywords: "halloween pumpkin lantern orange" },

    // People & Body
    { emoji: "👋", category: "people", name: "waving hand", keywords: "wave hand hello goodbye greeting" },
    { emoji: "🤚", category: "people", name: "raised back of hand", keywords: "hand back raise" },
    { emoji: "🖐️", category: "people", name: "hand with fingers splayed", keywords: "hand fingers spread" },
    { emoji: "✋", category: "people", name: "raised hand", keywords: "hand stop highfive raise" },
    { emoji: "🖖", category: "people", name: "vulcan salute", keywords: "vulcan salute spock space" },
    { emoji: "👌", category: "people", name: "OK hand", keywords: "ok hand okay correct good" },
    { emoji: "🤌", category: "people", name: "pinched fingers", keywords: "pinched fingers italian gesture" },
    { emoji: "🤏", category: "people", name: "pinching hand", keywords: "pinch small little hand" },
    { emoji: "✌️", category: "people", name: "victory hand", keywords: "victory peace hand two" },
    { emoji: "🤞", category: "people", name: "crossed fingers", keywords: "cross fingers luck hope" },
    { emoji: "🫰", category: "people", name: "hand with index finger and thumb crossed", keywords: "heart love finger snap kpop korean" },
    { emoji: "🤟", category: "people", name: "love-you gesture", keywords: "love you sign hand gesture" },
    { emoji: "🤘", category: "people", name: "sign of the horns", keywords: "horns metal rock hand gesture" },
    { emoji: "🤙", category: "people", name: "call me hand", keywords: "call phone hand gesture hangloose" },
    { emoji: "👈", category: "people", name: "backhand index pointing left", keywords: "point left hand backhand" },
    { emoji: "👉", category: "people", name: "backhand index pointing right", keywords: "point right hand backhand" },
    { emoji: "👆", category: "people", name: "backhand index pointing up", keywords: "point up hand backhand" },
    { emoji: "🖕", category: "people", name: "middle finger", keywords: "middle finger rude hand gesture" },
    { emoji: "👇", category: "people", name: "backhand index pointing down", keywords: "point down hand backhand" },
    { emoji: "☝️", category: "people", name: "index pointing up", keywords: "point up hand one" },
    { emoji: "👍", category: "people", name: "thumbs up", keywords: "thumbs up good like yes approve" },
    { emoji: "👎", category: "people", name: "thumbs down", keywords: "thumbs down bad dislike no reject" },
    { emoji: "✊", category: "people", name: "raised fist", keywords: "fist power punch strike solidarity" },
    { emoji: "👊", category: "people", name: "oncoming fist", keywords: "fist punch bump oncoming strike" },
    { emoji: "🤛", category: "people", name: "left-facing fist", keywords: "fist left punch bump" },
    { emoji: "🤜", category: "people", name: "right-facing fist", keywords: "fist right punch bump" },
    { emoji: "👏", category: "people", name: "clapping hands", keywords: "clap hands applaud praise" },
    { emoji: "🙌", category: "people", name: "raising hands", keywords: "raise hands celebrate victory holy" },
    { emoji: "👐", category: "people", name: "open hands", keywords: "open hands hug offer" },
    { emoji: "🤲", category: "people", name: "palms up together", keywords: "palms together pray book offer" },
    { emoji: "🤝", category: "people", name: "handshake", keywords: "handshake shake hands deal agreement trust" },
    { emoji: "🙏", category: "people", name: "folded hands", keywords: "pray please thank you namaste highfive" },
    { emoji: "✍️", category: "people", name: "writing hand", keywords: "write hand pen pencil draw" },
    { emoji: "💅", category: "people", name: "nail polish", keywords: "nail polish manicure cosmetics beauty" },
    { emoji: "🤳", category: "people", name: "selfie", keywords: "selfie camera phone photo hand" },
    { emoji: "💪", category: "people", name: "flexed biceps", keywords: "flex biceps muscle strong power workout fitness" },
    { emoji: "🦵", category: "people", name: "leg", keywords: "leg foot limb kick" },
    { emoji: "🦶", category: "people", name: "foot", keywords: "foot leg step kick walk" },
    { emoji: "👂", category: "people", name: "ear", keywords: "ear hear listen sound" },
    { emoji: "👃", category: "people", name: "nose", keywords: "nose smell sniff" },
    { emoji: "🧠", category: "people", name: "brain", keywords: "brain mind think smart intelligence" },
    { emoji: "🫀", category: "people", name: "anatomical heart", keywords: "heart anatomical organ doctor medicine" },
    { emoji: "🫁", category: "people", name: "lungs", keywords: "lungs organ breathe doctor medicine" },
    { emoji: "🦷", category: "people", name: "tooth", keywords: "tooth teeth dentist dentist dentist" },
    { emoji: "👀", category: "people", name: "eyes", keywords: "eyes look see watch peep look" },
    { emoji: "👅", category: "people", name: "tongue", keywords: "tongue mouth lick taste" },
    { emoji: "👄", category: "people", name: "mouth", keywords: "mouth lips talk speak" },
    { emoji: "💋", category: "people", name: "kiss mark", keywords: "kiss mark red lips makeup" },

    // Animals & Nature
    { emoji: "🐶", category: "animals", name: "dog face", keywords: "dog puppy pet animal face bark" },
    { emoji: "🐱", category: "animals", name: "cat face", keywords: "cat kitten pet animal face meow" },
    { emoji: "🐭", category: "animals", name: "mouse face", keywords: "mouse rat animal face squeak" },
    { emoji: "🐹", category: "animals", name: "hamster", keywords: "hamster pet animal face" },
    { emoji: "🐰", category: "animals", name: "rabbit face", keywords: "rabbit bunny pet animal face" },
    { emoji: "🦊", category: "animals", name: "fox", keywords: "fox animal face wild" },
    { emoji: "🐻", category: "animals", name: "bear", keywords: "bear wild animal face" },
    { emoji: "🐼", category: "animals", name: "panda", keywords: "panda china animal face" },
    { emoji: "🐨", category: "animals", name: "koala", keywords: "koala australia animal face" },
    { emoji: "🐯", category: "animals", name: "tiger face", keywords: "tiger wild animal face roar" },
    { emoji: "🦁", category: "animals", name: "lion", keywords: "lion wild animal face roar king" },
    { emoji: "🐮", category: "animals", name: "cow face", keywords: "cow farm animal face moo" },
    { emoji: "🐷", category: "animals", name: "pig face", keywords: "pig farm animal face oink" },
    { emoji: "🐸", category: "animals", name: "frog", keywords: "frog animal face ribbit croak" },
    { emoji: "🐵", category: "animals", name: "monkey face", keywords: "monkey animal face" },
    { emoji: "🐔", category: "animals", name: "chicken", keywords: "chicken bird farm animal cluck" },
    { emoji: "🐧", category: "animals", name: "penguin", keywords: "penguin bird ice cold animal" },
    { emoji: "🐦", category: "animals", name: "bird", keywords: "bird animal fly chirp" },
    { emoji: "🐣", category: "animals", name: "hatching chick", keywords: "chick egg baby bird hatch" },
    { emoji: "🦆", category: "animals", name: "duck", keywords: "duck bird farm animal quack" },
    { emoji: "🦅", category: "animals", name: "eagle", keywords: "eagle bird wild predator fly usa" },
    { emoji: "🦉", category: "animals", name: "owl", keywords: "owl bird night wise wild hoot" },
    { emoji: "🦇", category: "animals", name: "bat", keywords: "bat night vampire halloween animal fly" },
    { emoji: "🐺", category: "animals", name: "wolf", keywords: "wolf wild dog animal howl" },
    { emoji: "🐝", category: "animals", name: "honeybee", keywords: "bee honey insect bug buzz" },
    { emoji: "🦋", category: "animals", name: "butterfly", keywords: "butterfly insect bug fly beautiful color" },
    { emoji: "🐌", category: "animals", name: "snail", keywords: "snail slow bug shell animal" },
    { emoji: "🐞", category: "animals", name: "lady beetle", keywords: "ladybug ladybeetle insect bug red" },
    { emoji: "🐜", category: "animals", name: "ant", keywords: "ant insect bug team" },
    { emoji: "🕷️", category: "animals", name: "spider", keywords: "spider bug insect web halloween scary" },
    { emoji: "🦂", category: "animals", name: "scorpion", keywords: "scorpion bug insect wild sting hazard" },
    { emoji: "🐢", category: "animals", name: "turtle", keywords: "turtle slow shell reptile animal" },
    { emoji: "🐍", category: "animals", name: "snake", keywords: "snake reptile wild hiss hazard" },
    { emoji: "🐙", category: "animals", name: "octopus", keywords: "octopus sea ocean animal tentacles" },
    { emoji: "🐠", category: "animals", name: "tropical fish", keywords: "fish tropical ocean sea color swim pet" },
    { emoji: "🐬", category: "animals", name: "dolphin", keywords: "dolphin sea ocean smart animal swim jump" },
    { emoji: "🐳", category: "animals", name: "spouting whale", keywords: "whale ocean sea animal spouting water" },
    { emoji: "🦈", category: "animals", name: "shark", keywords: "shark predator ocean sea animal hazard swim" },
    { emoji: "🐊", category: "animals", name: "crocodile", keywords: "crocodile reptile wild swamp hazard animal" },
    { emoji: "🦖", category: "animals", name: "t-rex", keywords: "trex dinosaur extinct reptile monster animal" },
    { emoji: "🌵", category: "animals", name: "cactus", keywords: "cactus desert plant spike green" },
    { emoji: "🎄", category: "animals", name: "christmas tree", keywords: "christmas tree holiday celebration decoration" },
    { emoji: "🌲", category: "animals", name: "evergreen tree", keywords: "tree pine evergreen forest wood nature" },
    { emoji: "🌳", category: "animals", name: "deciduous tree", keywords: "tree deciduous forest wood nature green" },
    { emoji: "🌴", category: "animals", name: "palm tree", keywords: "tree palm beach resort warm summer island" },
    { emoji: "🌱", category: "animals", name: "seedling", keywords: "seedling plant grow sprout spring nature" },
    { emoji: "🌿", category: "animals", name: "herb", keywords: "herb plant leaf green health tea cooking" },
    { emoji: "🍀", category: "animals", name: "four leaf clover", keywords: "clover lucky four leaf green luck irish" },
    { emoji: "🍂", category: "animals", name: "fallen leaf", keywords: "leaf fallen autumn wind brown nature" },
    { emoji: "🍁", category: "animals", name: "maple leaf", keywords: "leaf maple autumn canada red nature" },
    { emoji: "🍄", category: "animals", name: "mushroom", keywords: "mushroom fungus toadstool forest nature" },
    { emoji: "🌹", category: "animals", name: "rose", keywords: "rose flower red love beautiful valentine" },
    { emoji: "🌸", category: "animals", name: "cherry blossom", keywords: "blossom cherry flower pink spring japan sakura" },
    { emoji: "🌻", category: "animals", name: "sunflower", keywords: "sunflower flower yellow summer sun seeds" },
    { emoji: "🌼", category: "animals", name: "blossom", keywords: "blossom flower yellow spring" },
    { emoji: "⭐", category: "animals", name: "star", keywords: "star yellow space night gold" },
    { emoji: "🔥", category: "animals", name: "fire", keywords: "fire flame hot burn cook warm" },
    { emoji: "🌈", category: "animals", name: "rainbow", keywords: "rainbow colors rain sky sun nature" },

    // Food & Drink
    { emoji: "🍏", category: "food", name: "green apple", keywords: "apple fruit green healthy food" },
    { emoji: "🍎", category: "food", name: "red apple", keywords: "apple fruit red healthy food" },
    { emoji: "🍌", category: "food", name: "banana", keywords: "banana fruit yellow potassium food" },
    { emoji: "🍉", category: "food", name: "watermelon", keywords: "watermelon fruit summer sweet food" },
    { emoji: "🍇", category: "food", name: "grapes", keywords: "grapes fruit wine purple food" },
    { emoji: "🍓", category: "food", name: "strawberry", keywords: "strawberry fruit red sweet berry food" },
    { emoji: "🍒", category: "food", name: "cherries", keywords: "cherries fruit red sweet couple food" },
    { emoji: "🍑", category: "food", name: "peach", keywords: "peach fruit orange sweet butt food" },
    { emoji: "🍍", category: "food", name: "pineapple", keywords: "pineapple fruit tropical yellow sweet food" },
    { emoji: "🥥", category: "food", name: "coconut", keywords: "coconut fruit tropical milk food" },
    { emoji: "🥑", category: "food", name: "avocado", keywords: "avocado fruit green healthy toast guacamole food" },
    { emoji: "🍆", category: "food", name: "eggplant", keywords: "eggplant vegetable purple food dick" },
    { emoji: "🥔", category: "food", name: "potato", keywords: "potato vegetable carb starch food" },
    { emoji: "🥕", category: "food", name: "carrot", keywords: "carrot vegetable orange rabbit healthy food" },
    { emoji: "🌽", category: "food", name: "ear of corn", keywords: "corn vegetable yellow farm food cob" },
    { emoji: "🥦", category: "food", name: "broccoli", keywords: "broccoli vegetable green tree healthy food" },
    { emoji: "🧅", category: "food", name: "onion", keywords: "onion vegetable cry flavor food" },
    { emoji: "🍄", category: "food", name: "mushroom", keywords: "mushroom fungus cooking food" },
    { emoji: "🧀", category: "food", name: "cheese wedge", keywords: "cheese dairy yellow swiss mouse food" },
    { emoji: "🍞", category: "food", name: "bread", keywords: "bread loaf carb baking food" },
    { emoji: "🥐", category: "food", name: "croissant", keywords: "croissant bread pastry french bakery food" },
    { emoji: "🥞", category: "food", name: "pancakes", keywords: "pancakes breakfast butter syrup cake food" },
    { emoji: "🍳", category: "food", name: "cooking", keywords: "egg frying pan breakfast cooking food" },
    { emoji: "🥓", category: "food", name: "bacon", keywords: "bacon pork breakfast meat food" },
    { emoji: "🍔", category: "food", name: "hamburger", keywords: "burger hamburger fastfood beef cheese food" },
    { emoji: "🍟", category: "food", name: "french fries", keywords: "fries frenchfries fastfood potato food" },
    { emoji: "🍕", category: "food", name: "pizza", keywords: "pizza fastfood cheese pepperoni slice food" },
    { emoji: "🌭", category: "food", name: "hot dog", keywords: "hotdog sausage fastfood bread food" },
    { emoji: "🥪", category: "food", name: "sandwich", keywords: "sandwich bread lunch food" },
    { emoji: "🌮", category: "food", name: "taco", keywords: "taco mexican fastfood wrap food" },
    { emoji: "🌯", category: "food", name: "burrito", keywords: "burrito mexican fastfood wrap food" },
    { emoji: "🍜", category: "food", name: "steaming bowl", keywords: "noodle ramen bowl soup japanese food" },
    { emoji: "🍣", category: "food", name: "sushi", keywords: "sushi raw fish rice japanese food" },
    { emoji: "🥟", category: "food", name: "dumpling", keywords: "dumpling potsticker dimsum food" },
    { emoji: "🍦", category: "food", name: "soft ice cream", keywords: "icecream softserve dairy dessert summer sweet food" },
    { emoji: "🍩", category: "food", name: "donut", keywords: "donut dough nut dessert sweet ring glaze food" },
    { emoji: "🍪", category: "food", name: "cookie", keywords: "cookie biscuit chocolate chip sweet dessert food" },
    { emoji: "🎂", category: "food", name: "birthday cake", keywords: "cake birthday celebration candle sweet dessert food" },
    { emoji: "🍫", category: "food", name: "chocolate bar", keywords: "chocolate sweet candy cocoa dessert food" },
    { emoji: "🍬", category: "food", name: "candy", keywords: "candy sweet sugar wrapper food" },
    { emoji: "🍯", category: "food", name: "honey pot", keywords: "honey pot sweet bear bee food" },
    { emoji: "☕️", category: "food", name: "hot beverage", keywords: "coffee tea cup hot cafe caffeine drink" },
    { emoji: "🍵", category: "food", name: "teacup without handle", keywords: "tea greentea matcha cup hot drink" },
    { emoji: "🍺", category: "food", name: "beer mug", keywords: "beer mug alcohol bar drink pub cheer" },
    { emoji: "🍻", category: "food", name: "clinking beer mugs", keywords: "beer mugs alcohol bar drink toast cheer" },
    { emoji: "🍷", category: "food", name: "wine glass", keywords: "wine glass alcohol red bar drink toast" },
    { emoji: "🥃", category: "food", name: "tumbler glass", keywords: "whiskey glass alcohol rum shot drink toast" },
    { emoji: "🥤", category: "food", name: "cup with straw", keywords: "soda straw drink cup shake" },
    { emoji: "🧋", category: "food", name: "bubble tea", keywords: "boba bubble tea milk drink pearl" },

    // Activities
    { emoji: "⚽", category: "activities", name: "soccer ball", keywords: "soccer football sport ball play match" },
    { emoji: "🏀", category: "activities", name: "basketball", keywords: "basketball sport ball play hoop match" },
    { emoji: "🏈", category: "activities", name: "american football", keywords: "football american sport ball play match" },
    { emoji: "⚾", category: "activities", name: "baseball", keywords: "baseball sport ball play match" },
    { emoji: "🎾", category: "activities", name: "tennis", keywords: "tennis sport ball play racket match" },
    { emoji: "🏐", category: "activities", name: "volleyball", keywords: "volleyball sport ball play net" },
    { emoji: "🎱", category: "activities", name: "billiards", keywords: "billiards pool 8ball sport game" },
    { emoji: "🏓", category: "activities", name: "ping pong", keywords: "pingpong table tennis sport paddle ball game" },
    { emoji: "🏸", category: "activities", name: "badminton", keywords: "badminton racket birdie sport game" },
    { emoji: "⛳", category: "activities", name: "flag in hole", keywords: "golf hole flag green club sport game" },
    { emoji: "🥊", category: "activities", name: "boxing glove", keywords: "boxing glove punch fight sport" },
    { emoji: "🛹", category: "activities", name: "skateboard", keywords: "skateboard board skate sport ride" },
    { emoji: "🏋️", category: "activities", name: "person lifting weights", keywords: "weightlifting gym fitness lifting exercise strong sport" },
    { emoji: "🧘", category: "activities", name: "person in lotus position", keywords: "yoga meditation zen calm peace health mindfulness" },
    { emoji: "🚴", category: "activities", name: "person biking", keywords: "cycling bicycle bike ride sport exercise" },
    { emoji: "🏆", category: "activities", name: "trophy", keywords: "trophy prize winner first champion gold success" },
    { emoji: "🥇", category: "activities", name: "1st place medal", keywords: "medal prize winner first champion gold success" },
    { emoji: "🥈", category: "activities", name: "2nd place medal", keywords: "medal prize winner second silver success" },
    { emoji: "🥉", category: "activities", name: "3rd place medal", keywords: "medal prize winner third bronze success" },
    { emoji: "🎗️", category: "activities", name: "reminder ribbon", keywords: "ribbon support awareness event" },
    { emoji: "🎟️", category: "activities", name: "admission tickets", keywords: "ticket admission movie concert show entry" },
    { emoji: "🎨", category: "activities", name: "artist palette", keywords: "palette paint brush art color draw creative" },
    { emoji: "🎬", category: "activities", name: "clapper board", keywords: "clapper movie film cinema shoot act director" },
    { emoji: "🎤", category: "activities", name: "microphone", keywords: "microphone mic sing music karaoke song sound" },
    { emoji: "🎧", category: "activities", name: "headphone", keywords: "headphone music song sound listen audio" },
    { emoji: "🎸", category: "activities", name: "guitar", keywords: "guitar instrument music song sound play" },
    { emoji: "🎹", category: "activities", name: "musical keyboard", keywords: "piano keyboard instrument music song sound play" },
    { emoji: "🎮", category: "activities", name: "video game", keywords: "gamepad controller play nintendo playstation xbox arcade" },
    { emoji: "🎲", category: "activities", name: "game die", keywords: "dice die boardgame roll play luck" },
    { emoji: "🎯", category: "activities", name: "bullseye", keywords: "target dart arrow hit bullseye success goal" },

    // Travel & Places
    { emoji: "🚗", category: "travel", name: "automobile", keywords: "car auto vehicle travel drive road" },
    { emoji: "🚕", category: "travel", name: "taxi", keywords: "taxi cab vehicle yellow travel drive city" },
    { emoji: "🚓", category: "travel", name: "police car", keywords: "police car vehicle law siren cop" },
    { emoji: "🚒", category: "travel", name: "fire engine", keywords: "fire engine truck siren rescue emergency" },
    { emoji: "🛵", category: "travel", name: "motor scooter", keywords: "scooter vespa motorcycle vehicle ride" },
    { emoji: "🚲", category: "travel", name: "bicycle", keywords: "bicycle bike vehicle ride exercise" },
    { emoji: "🚂", category: "travel", name: "locomotive", keywords: "train engine railway travel vehicle" },
    { emoji: "✈️", category: "travel", name: "airplane", keywords: "airplane plane airport fly flight travel sky" },
    { emoji: "🚀", category: "travel", name: "rocket", keywords: "rocket space launch ship travel nasa" },
    { emoji: "🛸", category: "travel", name: "ufo", keywords: "ufo space alien flying saucer mystery" },
    { emoji: "🚁", category: "travel", name: "helicopter", keywords: "helicopter chopper fly travel sky copter" },
    { emoji: "⚓", category: "travel", name: "anchor", keywords: "anchor ship boat port sea ocean navy" },
    { emoji: "⛵", category: "travel", name: "sailboat", keywords: "boat sailboat sea ocean wind travel sail" },
    { emoji: "🚢", category: "travel", name: "ship", keywords: "ship boat cruise ocean sea travel port" },
    { emoji: "🚨", category: "travel", name: "police car light", keywords: "siren police alarm emergency warning red blue" },
    { emoji: "🚥", category: "travel", name: "horizontal traffic light", keywords: "traffic light signal stop go road intersection" },
    { emoji: "🚦", category: "travel", name: "vertical traffic light", keywords: "traffic light signal stop go road intersection" },
    { emoji: "🛑", category: "travel", name: "stop sign", keywords: "stop sign red road rule" },
    { emoji: "🗺️", category: "travel", name: "world map", keywords: "map travel explore adventure geography paper" },
    { emoji: "🌋", category: "travel", name: "volcano", keywords: "volcano eruption lava fire mountain island hot" },
    { emoji: "🗻", category: "travel", name: "mount fuji", keywords: "mountain fuji snow japan peak nature" },
    { emoji: "🏕️", category: "travel", name: "camping", keywords: "camping tent forest campfire outdoor nature" },
    { emoji: "🏖️", category: "travel", name: "beach with umbrella", keywords: "beach umbrella sand ocean sea summer resort" },
    { emoji: "🏜️", category: "travel", name: "desert", keywords: "desert sand cactus sun dry hot empty" },
    { emoji: "🏝️", category: "travel", name: "desert island", keywords: "island tropical beach palm tree ocean sea resort" },
    { emoji: "🏠", category: "travel", name: "house", keywords: "house home building realestate residential" },
    { emoji: "🏢", category: "travel", name: "office building", keywords: "office building business company city work" },
    { emoji: "🏥", category: "travel", name: "hospital", keywords: "hospital doctor nurse medicine health emergency" },
    { emoji: "🏫", category: "travel", name: "school", keywords: "school education teacher student study class" },
    { emoji: "🏰", category: "travel", name: "castle", keywords: "castle fort palace fantasy medieval royal disney" },
    { emoji: "🗼", category: "travel", name: "tokyo tower", keywords: "tower tokyo paris eiffel red building landmark" },
    { emoji: "🗽", category: "travel", name: "statue of liberty", keywords: "statue liberty usa newyork landmark green" },
    { emoji: "⛪", category: "travel", name: "church", keywords: "church religion cross christian building" },

    // Objects
    { emoji: "💻", category: "objects", name: "laptop", keywords: "laptop computer screen work code tech macbook pc" },
    { emoji: "⌨️", category: "objects", name: "keyboard", keywords: "keyboard computer typing key board tech input" },
    { emoji: "🖥️", category: "objects", name: "desktop computer", keywords: "computer desktop screen monitor tech" },
    { emoji: "🖨️", category: "objects", name: "printer", keywords: "printer paper ink office print document" },
    { emoji: "📱", category: "objects", name: "mobile phone", keywords: "phone smartphone mobile call screen iphone android tech" },
    { emoji: "📷", category: "objects", name: "camera", keywords: "camera photo lens snapshot picture shoot tech" },
    { emoji: "📹", category: "objects", name: "video camera", keywords: "camera video record movie film tech" },
    { emoji: "📺", category: "objects", name: "television", keywords: "tv television screen show movie video tech" },
    { emoji: "🎙️", category: "objects", name: "studio microphone", keywords: "microphone mic podcast audio sound recording" },
    { emoji: "🔋", category: "objects", name: "battery", keywords: "battery power charge energy electricity tech" },
    { emoji: "🔌", category: "objects", name: "electric plug", keywords: "plug electricity wire power connect outlet tech" },
    { emoji: "💡", category: "objects", name: "light bulb", keywords: "lightbulb light bulb lamp idea inspiration energy" },
    { emoji: "🕯️", category: "objects", name: "candle", keywords: "candle flame wax fire light burn quiet cozy" },
    { emoji: "💵", category: "objects", name: "dollar banknote", keywords: "dollar money cash banknote green paper rich" },
    { emoji: "🪙", category: "objects", name: "coin", keywords: "coin money cash gold silver bronze cent metal" },
    { emoji: "💰", category: "objects", name: "money bag", keywords: "money bag cash gold rich coin wealth" },
    { emoji: "💳", category: "objects", name: "credit card", keywords: "card creditcard money pay shopping bank tech" },
    { emoji: "💎", category: "objects", name: "gem stone", keywords: "diamond gem jewel stone blue diamond diamond jewelry shiny" },
    { emoji: "🔧", category: "objects", name: "wrench", keywords: "wrench tool fix spanner mechanic repair" },
    { emoji: "🔨", category: "objects", name: "hammer", keywords: "hammer tool build fix nail strike" },
    { emoji: "⚙️", category: "objects", name: "gear", keywords: "gear cog machine settings engineering process" },
    { emoji: "🔒", category: "objects", name: "locked", keywords: "lock locked secure safety key privacy" },
    { emoji: "🔓", category: "objects", name: "unlocked", keywords: "lock unlocked open safety privacy" },
    { emoji: "🔑", category: "objects", name: "key", keywords: "key unlock open lock secure password" },
    { emoji: "📦", category: "objects", name: "package", keywords: "package box delivery parcel post mail shipping cardboard" },
    { emoji: "✉️", category: "objects", name: "envelope", keywords: "envelope letter mail post email paper message" },
    { emoji: "📝", category: "objects", name: "memo", keywords: "memo note paper write pencil text list draft" },
    { emoji: "📅", category: "objects", name: "calendar", keywords: "calendar date day month schedule event time" },
    { emoji: "📎", category: "objects", name: "paperclip", keywords: "paperclip clip attach paper office hold" },
    { emoji: "✂️", category: "objects", name: "scissors", keywords: "scissors cut paper shear tool" },
    { emoji: "🗑️", category: "objects", name: "trash bin", keywords: "trash bin garbage waste delete empty rubish" },

    // Symbols
    { emoji: "❤️", category: "symbols", name: "red heart", keywords: "heart red love valentine romance like favorite" },
    { emoji: "🧡", category: "symbols", name: "orange heart", keywords: "heart orange love valentine romance like" },
    { emoji: "💛", category: "symbols", name: "yellow heart", keywords: "heart yellow love valentine romance like" },
    { emoji: "💚", category: "symbols", name: "green heart", keywords: "heart green love valentine romance like" },
    { emoji: "💙", category: "symbols", name: "blue heart", keywords: "heart blue love valentine romance like" },
    { emoji: "💜", category: "symbols", name: "purple heart", keywords: "heart purple love valentine romance like military" },
    { emoji: "🖤", category: "symbols", name: "black heart", keywords: "heart black love valentine romance like sad dark" },
    { emoji: "🤍", category: "symbols", name: "white heart", keywords: "heart white love valentine romance like" },
    { emoji: "🤎", category: "symbols", name: "brown heart", keywords: "heart brown love valentine romance like" },
    { emoji: "💔", category: "symbols", name: "broken heart", keywords: "heart broken sad heartbreak split grief" },
    { emoji: "❣️", category: "symbols", name: "heart exclamation", keywords: "heart exclamation punctuation mark red" },
    { emoji: "💕", category: "symbols", name: "two hearts", keywords: "hearts love couple sweet pink" },
    { emoji: "💞", category: "symbols", name: "revolving hearts", keywords: "hearts love revolving spinning pink" },
    { emoji: "✨", category: "symbols", name: "sparkles", keywords: "sparkles shine clean star magic new" },
    { emoji: "🌟", category: "symbols", name: "glowing star", keywords: "star glow yellow space shine magic success" },
    { emoji: "💥", category: "symbols", name: "collision", keywords: "collision explode blast crash comic boom" },
    { emoji: "💯", category: "symbols", name: "hundred points", keywords: "100 hundred score perfect exam success good red" },
    { emoji: "💤", category: "symbols", name: "zzz", keywords: "zzz sleep tired snoring dream" },
    { emoji: "🌀", category: "symbols", name: "cyclone", keywords: "cyclone spiral wind storm blue" },
    { emoji: "🎵", category: "symbols", name: "musical note", keywords: "note music song sound melody" },
    { emoji: "🎶", category: "symbols", name: "musical notes", keywords: "notes music song sound melody" },
    { emoji: "🔔", category: "symbols", name: "bell", keywords: "bell ring notification alert sound" },
    { emoji: "💭", category: "symbols", name: "thought balloon", keywords: "thought bubble balloon think dream cloud" },
    { emoji: "✔️", category: "symbols", name: "check mark", keywords: "check mark correct ok yes tick" },
    { emoji: "❌", category: "symbols", name: "cross mark", keywords: "cross mark wrong no incorrect delete x" },
    { emoji: "⚠️", category: "symbols", name: "warning", keywords: "warning hazard alert danger sign yellow triangle" },
    { emoji: "ℹ️", category: "symbols", name: "information", keywords: "info information blue sign guide" },
    { emoji: "♿", category: "symbols", name: "wheelchair symbol", keywords: "wheelchair handicap accessibility blue sign" },
    { emoji: "♻️", category: "symbols", name: "recycling symbol", keywords: "recycle recycling green arrow environment" },
    { emoji: "🌐", category: "symbols", name: "globe with meridians", keywords: "globe meridians world internet network web earth" }
];
