cursor            #84d5c4
cursor_text_color #00382f

foreground            #dee4e1
background            #090f0e
selection_foreground  #1c352f
selection_background  #b1ccc4
url_color             #b1ccc4

#: black 000000 767676
color0  #0e1513
color8  #303634
#: red cc0403 f2201f
color1  #001914
color9  #03af92
#: green 19cb00 23fd00
color2  #b1ccc4
color10 #cde8e0
#: yellow cecb00 fffd00
color3  #abcae4
color11 #c9e6ff
#: blue 0d73cc 1a8fff
color4  #005045
color12 #84d5c4
#: magenta cb1ed1 fd28ff
color5  #334b46
color13 #b1ccc4
#: cyan 0dcdcd 14ffff
color6  #2b4a5f
color14 #abcae4
#: white dddddd ffffff
color7  #bec9c5
color15 #dee4e1

mark1_foreground #00201b
mark1_background #a0f2df
mark2_foreground #06201b
mark2_background #cde8e0
mark3_foreground #001e2f
mark3_background #c9e6ff

active_tab_foreground #00382f
active_tab_background #84d5c4
inactive_tab_foreground #a0f2df
inactive_tab_background #005045

active_border_color #84d5c4
inactive_border_color #00382f
# bell_border_color #ff5a00
